### ISSUE TITLE
Error: [CM6] tree.iterate has changed syntax.

### ISSUE THREAD

**Issue by KuSi833** [elias-sundqvist/obsidian-react-components#41]
I'm encountering into the following error in the Obsidian console when using the plugin:

```
app.js:1 Error: [CM6] tree.iterate has changed syntax.
See the stack trace to find the faulty plugin and file an issue with the plugin author. 
Details: https://discuss.codemirror.net/t/release-0-20-0/4302
    at app.js:1:1045852
    at e.iterate (app.js:1:501709)
    at e.Uc.iterate (app.js:1:1046086)
    at LivePlugin.build (plugin:obsidian-reac…omponents:145519:59)
    at LivePlugin.update (plugin:obsidian-reac…omponents:145480:26)
    at e.update (app.js:1:350332)
    at e.updatePlugins (app.js:1:440837)
    at e.update (app.js:1:439009)
    at e._dispatch (app.js:1:436036)
    at e.dispatch (app.js:1:437814)
(anonymous)	@	app.js:1
e.iterate	@	app.js:1
Uc.iterate	@	app.js:1
build	@	plugin:obsidian-react-components:145519
update	@	plugin:obsidian-react-components:145480
e.update	@	app.js:1
e.updatePlugins	@	app.js:1
e.update	@	app.js:1
_dispatch	@	app.js:1
e.dispatch	@	app.js:1
(anonymous)	@	app.js:1
setTimeout (async)		
cN	@	app.js:1
focus	@	app.js:1
e.runCustomHandlers	@	app.js:1
(anonymous)	@	app.js:1
```

It hasn't affected any of the functionality.

**Comment by yinguohang** [comment]
Same here, tons observed.

**Comment by Fengyee** [comment]
Me too, try to switch back to this plugin downloaded from another place https://github.com/PKM-er/Blue-topaz-example resolves the console output.
